spec:
  replicas: ${replicaCount}
  template:
    spec:
      containers:
        - name: ${containerName}
          imagePullPolicy: ${imagePullPolicy}
          env:
            - name: DEMO_JKUBE_GREETING
              value: ${demoGreeting}
