spec:
  replicas: ${deployment.replicas}
  template:
    spec:
      containers:
        - name: ${deployment.container.name}
          imagePullPolicy: ${deployment.container.imagePullPolicy}
          env:
            - name: DEMO_JKUBE_GREETING
              value: ${application.greeting}
